# Generated by Django 4.2.11 on 2026-04-19 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "benevity_file",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/benevity/"
                    ),
                ),
                (
                    "fup_file",
                    models.FileField(blank=True, null=True, upload_to="uploads/fup/"),
                ),
                (
                    "paypal_file",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/paypal/"
                    ),
                ),
                (
                    "stripe_file",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/stripe/"
                    ),
                ),
                (
                    "globalgiving_file",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/globalgiving/"
                    ),
                ),
                (
                    "bb_file",
                    models.FileField(blank=True, null=True, upload_to="uploads/bb/"),
                ),
                ("total_donors", models.IntegerField(default=0)),
                ("unique_donors", models.IntegerField(default=0)),
                ("unmatched_donors", models.IntegerField(default=0)),
                ("matched_donors", models.IntegerField(default=0)),
                ("match_rate", models.FloatField(default=0.0)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("source_breakdown", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("success", "Success"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="analyzer.analysissession",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UnmatchedDonor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("benevity", "BENEVITY"),
                            ("fup", "FUP RAW"),
                            ("paypal", "PAYPAL"),
                            ("stripe", "STRIPE"),
                            ("globalgiving", "GLOBALGIVING"),
                        ],
                        max_length=20,
                    ),
                ),
                ("import_id", models.CharField(blank=True, max_length=20)),
                ("imported", models.BooleanField(default=False)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donors",
                        to="analyzer.analysissession",
                    ),
                ),
            ],
            options={
                "ordering": ["source", "last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["analysis", "source"],
                        name="analyzer_un_analysi_533294_idx",
                    ),
                    models.Index(fields=["email"], name="analyzer_un_email_aa6622_idx"),
                    models.Index(
                        fields=["imported"], name="analyzer_un_importe_30df1f_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="analysissession",
            index=models.Index(
                fields=["-created_at"], name="analyzer_an_created_777b8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysissession",
            index=models.Index(fields=["status"], name="analyzer_an_status_c5385e_idx"),
        ),
        migrations.AddIndex(
            model_name="analysissession",
            index=models.Index(fields=["user"], name="analyzer_an_user_id_25a483_idx"),
        ),
    ]
